-- MODULOS - REAL-A
INSERT INTO module(oid, moduleid, modulename) VALUES (1,'sv2','Acceso Usuarios');
INSERT INTO module(oid, moduleid, modulename) VALUES (2,'sv3','Repositorio Imagenes');
INSERT INTO module(oid, moduleid, modulename) VALUES (3,'sv6','Acceso Usuario Movil');
INSERT INTO module(oid, moduleid, modulename) VALUES (4,'sv7','Repositorio Imagenes Movil');

-- GRUPOS - REAL-A
INSERT INTO "group"(oid, groupname, module_oid) VALUES (1,'Usuarios',1);
INSERT INTO "group"(oid, groupname, module_oid) VALUES (2,'Admin',2);

-- RELACIÓN GRUPOS-MODULOS - REAL-A
INSERT INTO group_module(group_oid, module_oid) VALUES (1, 1);
INSERT INTO group_module(group_oid, module_oid) VALUES (1, 3);
INSERT INTO group_module(group_oid, module_oid) VALUES (2, 1);
INSERT INTO group_module(group_oid, module_oid) VALUES (2, 2);
INSERT INTO group_module(group_oid, module_oid) VALUES (2, 3);
INSERT INTO group_module(group_oid, module_oid) VALUES (2, 4);

-- USUARIOS - REAL-A
INSERT INTO "user"(oid, username, "password", email, group_oid) VALUES (2,'Admin','SOscL3u2VUE=','administrador@reala.es',2);
INSERT INTO "user"(oid, username, "password", email, group_oid) VALUES (9,'a','bUWbxy0GXyU=','usuario@reala.es',1);

-- RELACIÓN USUARIOS-GRUPOS - REAL-A
INSERT INTO user_group(user_oid, group_oid) VALUES (2, 2);
INSERT INTO user_group(user_oid, group_oid) VALUES (9, 1);

-- IDIOMA
INSERT INTO idioma(oid, descripcion, "language", country, flag) VALUES (2,'Spanish','es','ES','upload/userfiles/image/IdSpanish.gif');
INSERT INTO idioma(oid, descripcion, "language", country, flag) VALUES (3,'English','en','US','upload/userfiles/image/IdEnglish.gif');

--ARCO DE LA ESTRELLA
INSERT INTO objeto(oid, descripcion) VALUES (10,'Arco de la Estrella');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (11, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/1-1.JPG', 10);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (12, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/1-2.JPG', 10);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (13, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/1-3.JPG', 10);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (10, 'Arco de la Estrella','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Arco de la Estrella" width="190" height="143" src="upload/userfiles/image/1-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Se cuenta que el origen de la Puerta Nueva fue un boquete realizado en uno de los muchos combates que tuvo que sufrir esta muralla. La Torre de los Púlpitos se construyó para protegerla. La quinta y más reciente puerta de muralla. Une la Plaza Mayor con la Plaza de Santa María ambos centros neurálgicos de la ciudad durante varios siglos. Esta puerta-arco fue construida en 1726 por Larra Churriguera transformando una anterior conocida como La Puerta Nueva del siglo XV, que atravesaron en alguna ocasión los Reyes Católicos. El actual arco, tiene esta peculiar forma para permitir el paso de carruajes. En su parte interior posee una hornacina barroca con la imagen de La Virgen de la Estrella y un farolillo también con forma de estrella.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">A esta imagen se confiaban los viajeros cuando salían de la ciudad y a ella agradecían la vuelta.</p></span></td></tr></tbody></table><p>&nbsp;</p>', 10, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (11, 'Arch de la Estrella','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Arch de la Estrella" width="190" height="143" src="upload/userfiles/image/1-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">It is said that the origin of the New Bridge was a hole made in the wall in one of the many fights it suffered. The Tower de los Púlpitos was built to protect it.The fifth and most recent of the wall’s gates. It joins Plaza Mayor with the Plaza de Santa María, both of which have been key centres of the city for several centuries. This gate-arch was built in 1726 by Larra Churriguera, transforming an earlier one known as the New Gate, from the 15th century, which the Catholic Kings once passed through.The present arch has a peculiar shape to allow carriages to pass through. On the inside there is a Baroque niche with an image of the Virgin de la Estrella and a lantern, which is also in the shape of a star.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Travellers ask for protection from this image when they leave the city and thank it on their return.</p></span></td></tr></tbody></table><p>&nbsp;</p>', 10, 3);

--PALACIO EPISCOPAL
INSERT INTO objeto(oid, descripcion) VALUES (20,'Palacio Episcopal');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (21, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/2-1.JPG', 20);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (22, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/2-2.JPG', 20);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (23, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/2-3.JPG', 20);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (20,'Palacio Episcopal','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palacio Episcopal" width="190" height="143" src="upload/userfiles/image/2-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Este elegante palacio se encuentra en un lateral de la Plaza de Santa María que mandó reedificar el obispo cauriense Pedro García de Galarza a finales del siglo XVI, y cuyo escudo se puede apreciar sobre la ventana central de la segunda planta. Destaca su elegante portada de arco de medio punto con doble almohadillado de sillería, flanqueada por dos medallones que representan a un indio y una india americanos. Este palacio consta de dos portadas más, la procedente del antiguo seminario de San Pedro, fundado en siglo XVII por el mismo obispo Galarza y que se trasladó hasta aquí tras su derribo; y de la calle del Arco de la Estrella. La situación de esta hermosa construcción, cuyas traseras daban al adarve y a la Puerta Nueva, fue motivo de los pleitos tenidos con el Marqués de la Quinta de la Enjarada por abrir y remodelar el Arco de la Estrella, para dar paso a sus carruajes. En la actualidad es residencia del Obispo de la Diócesis de Coria-Cáceres.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Situada en Plaza de Santa María</p></span></td></tr></tbody></table><p>&nbsp;</p>',20, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (21,'Episcopal Palace','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Episcopal Palace" width="190" height="143" src="upload/userfiles/image/2-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">This elegant palace is on one side of the Plaza of Santa María. It was rebuilt on the orders of the Bishop Pedro García de Galarza, of Coria, at the end of the 16th century, whose shield can be seen over the central window of the second floor. It has an elegant facade with semi-circular arches with a double masonry bolster, flanked by two medallions that represent a male and female American Indian. This palace has two more facades, one from the former Seminary of San Pedro, founded in the 17th century by the same Bishop Galarza and moved here after its demolition; and the other on the street Arco de la Estrella. The location of this beautiful building, the back of which faces onto the city walls and the Puerta Nueva (New Gate), was the cause of legal disputes with the Marquis de la Quinta de la Enjarada to open and remodel the Arch de la Estrella, so his carriages could pass through. Nowadays it is the residence of the Bishop of the Diocese of Coria-Caceres.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Located in Plaza de Santa María.</p></span></td></tr></tbody></table><p>&nbsp;</p>',20, 3);

--CASA DE MAYORAZGO
INSERT INTO objeto(oid, descripcion) VALUES (30,'Casa de Mayorazgo');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (31, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/3-1.JPG', 30);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (32, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/3-2.JPG', 30);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (33, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/3-3.JPG', 30);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (30,'Palacio de Mayoralgo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palacio de Mayoralgo" width="190" height="143" src="upload/userfiles/image/3-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Como algunos de los edificios que se ubican junto al adarve, este tiene un pequeño arco-puente que comunica con la muralla y con la torre defensiva de la misma. Señorial mansión de una familia que fundó un importante mayorazgo, el primero de la provincia y uno de los más antiguos de España. La fachada está reformada, pues quedó destruida por una bomba que cayó en la plaza de Santa María durante la guerra civil en 1937. De todas maneras, el edificio tiene diversas fases constructivas. De estilo Gótico es la fachada lateral y el patio. De finales del XV principios del XVI es su fachada principal. En ella destacan dos bellas ventanas geminadas con mainel central en mármol y el escudo de la familia.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Este edificio ha sido habitado ininterrumpidamente por los sucesores de la familia hasta que lo adquirió la Caja de Ahorros de Extremadura para ubicar su sede social e institucional. Durante las obras de rehabilitación aparecieron en el jardín importantes restos arqueológicos.</p></span></td></tr></tbody></table><p>&nbsp;</p>',30, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (31,'Palace of Mayoralgo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palace of Mayoralgo" width="190" height="143" src="upload/userfiles/image/3-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Like some of the buildings located next to the adarve (walkway), it has a small arch-bridge that connects it to the wall and its defence tower the Centre of Interpretation de las Tres Culturas.Stately home of a family that founded an important entailed estate, the first in the province and one of the oldest in Spain.The facade has been restored as it was destroyed by a bomb that fell in the Plaza of Santa María in 1937 during the civil war. Besides this the building has gone through various constructive phases. It has a Gothic style side facade and patio. The main facade is from the end of the 15th and the start of the 16th century and has two beautiful double windows with marble central mullions and the family shield.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">This building was continuously inhabited by the family heirs until it was acquired by the Caja de Ahorros of Extremadura to house its social and institutional headquarters. During the restoration work carried out important archaeological remains appeared in the garden.</p></span></td></tr></tbody></table><p>&nbsp;</p>',30, 3);

--CASA DE LOS OBANDO
INSERT INTO objeto(oid, descripcion) VALUES (40,'Casa de los Obando');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (41, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/4-1.JPG', 40);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (42, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/4-2.JPG', 40);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (43, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/4-3.JPG', 40);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (40,'Palacio de Hernando de Ovando','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palacio de Hernando de Ovando" width="190" height="143" src="upload/userfiles/image/4-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Levantado en el siglo XVI, muy cercano a la iglesia de Santa María. En la fachada posee un escudo esgrafiado del XVIII, en el que aparecen representados los linajes familiares que lo habitaron. El edificio se compone de cuatro crujías en torno a un patio claustrado. Sobre la puerta de entrada al primer piso de la torre hay una inscripción que se refiere al año 1480. Desde ese punto el acceso a la parte superior se realiza a través de varios tramos de escalera adosados a los muros.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Situado en Plaza de Santa María.</p></span></td></tr></tbody></table><p>&nbsp;</p>',40, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (41,'Palace of Hernando de Ovando','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palace of Hernando de Ovando" width="190" height="143" src="upload/userfiles/image/4-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Built in the 16th century, very close to the Church of Santa María. On the facade there is a sgraffito shield from the 18th century, in which the family lineages of those who lived here are represented. The building is made up of four areas around a cloistered patio. Over the door to the first floor of the tower there is an inscription that refers to the year 1480. From here access to the upper sections is via several stairways that are up against the walls.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Located in Plaza de Santa María.</p></span></td></tr></tbody></table><p>&nbsp;</p>',40, 3);

--CASA Y TORRE CARBAJAL
INSERT INTO objeto(oid, descripcion) VALUES (50,'Casa y Torre Carbajal');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (51, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/5-1.JPG', 50);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (52, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/5-2.JPG', 50);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (53, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/5-3.JPG', 50);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (50,'Casa y Torre Carbajal','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa y Torre Carbajal" width="190" height="143" src="upload/userfiles/image/5-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Su fachada sigue la tipología típica de los palacios cacereños con balcón de esquina, escudo frontal de grandes dimensiones y puerta en arco de medio punto con dovelas radiales. Su huerto - del que destaca la higuera - es un claro ejemplo de los espacios verdes interiores que pueden encontrarse aún hoy en estas edificaciones de la Zona Monumental.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">En este edificio se encuentran las dependencias del Patronato de Turismo y Artesanía de la Diputación y el Centro de Interpretación de las Comarcas de la Provincia de Cáceres.</p></span></td></tr></tbody></table><p>&nbsp;</p>',50, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (51,'House and Tower Carbajal','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="House and Tower Carbajal" width="190" height="143" src="upload/userfiles/image/5-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Its facade is in keeping with the typical typology of the palaces in Caceres; with a corner balcony, a large shield at the front and a door in a semi-circular arch with radial voussoirs.Its orchard, with an outstanding fig tree, is a clear example of the inner green areas that you can still find today in these buildings within the Monumental Area.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">The offices of the Board of Tourism and Handicrafts of the Provincial Council and the Centre of Interpretation of the Regions of the Province of Caceres are in this building.</p></span></td></tr></tbody></table><p>&nbsp;</p>',50, 3);

--IGLESIA DE SANTAMARíA
INSERT INTO objeto(oid, descripcion) VALUES (60,'Iglésia de Santa María');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (61, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/6-1.JPG', 60);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (62, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/6-2.JPG', 60);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (63, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/6-3.JPG', 60);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (60,'Iglesia Concatedral de Santa María','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Iglesia Concatedral de Santa María" width="190" height="143" src="upload/userfiles/image/6-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">En la esquina, la escultura de San Pedro de Alcántara, del extremeño Enrique Pérez Comendador, tiene fama de atraer la suerte si le tocan los dedos de los pies, de ahí su brillo. Es la Iglesia principal de la ciudad. Fue construida entre los siglos XV al XVI sobre una obra anterior. Las portadas siguen modelos góticos y en la del Evangelio destaca un pilar con ménsula sosteniendo la Virgen. La torre es de tres cuerpos, el central tiene un medallón con jarrón de azucenas, símbolo de la Vírgen. El interior es de planta rectangular de tres naves, con arcos apuntados y bóvedas de crucería. Destaca su retablo del siglo XVI de cedro y pino sin policromar dedicado a la Asunción de la Virgen, realizado por Roque Balduque y Guillen Ferrant. Célebres son las capillas de los Carvajal, con un retablo barroco con San Miguel Arcángel del XVII, y la del Cristo Negro, imagen del siglo XV.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">En un banco esculpido en la portada principal se reunía antiguamente el Concejo Municipal.</p></span></td></tr></tbody></table><p>&nbsp;</p>',60, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (61,'Church Co-cathedral of Santa María','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Church Co-cathedral of Santa María" width="190" height="143" src="upload/userfiles/image/6-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">In the corner, the sculpture of San Pedro de Alcantara, by Enrique Pérez Comendador of Extremadura, is reputed to bring you luck if you touch its toes, which is why they are shiny.This is the city’s main church. It was built between the 15th and 16th centuries over an earlier building. It has Gothic facades and on the Gospel side there is a pillar with a corbel supporting the Virgin. The tower has three sections; the central one has a medallion with a vase of Madonna lilies, the symbol of the Virgin.Inside it is a rectangular building with three naves, with pointed arches and ribbed vaults. The altarpiece, from the 16th century, is made of cedar and pine, without polychrome, and is dedicated to the Assumption of the Virgin. It was made by Roque Balduque and Guillen Ferrant. The Chapels de los Carvajal are famous, with a Baroque altarpiece with Saint Michael the Archangel from the 17th century and Cristo Negro, an image from the 15th century.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">The Council meets on a carved bench outside the church after the Main Mass.</p></span></td></tr></tbody></table><p>&nbsp;</p>',60, 3);

--CASA DE LOS MORAGAS
INSERT INTO objeto(oid, descripcion) VALUES (70,'Casa de los Moragas');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (71, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/7-1.JPG', 70);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (72, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/7-2.JPG', 70);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (73, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/7-3.JPG', 70);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (70,'Casa de los Moragas','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa de los Moragas" width="190" height="143" src="upload/userfiles/image/7-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Se trata de una casa del siglo XV adquirida por la Diputación Provincial de Cáceres que tras una importante rehablitación se convierte en el Centro Provincial de Artesania.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">La Casa Moraga expone una muestra representativa de la artesanía extremeña: alfarería, cestería, cobre, corcho, forja, madera, tejidos, orivería, etc.</p></span></td></tr></tbody></table><p>&nbsp;</p>',70, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (71,'House of Moragas','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="House of Moragas" width="190" height="143" src="upload/userfiles/image/7-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">It is a XV century house acquired by the Provincial Council of Cáceres after major rehablitación becomes the Provincial Center for Crafts.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Moraga House presents a representative sample of the craft Extremadura: pottery, basketry, copper, cork, forging, wood, fabric, etc.</p></span></td></tr></tbody></table><p>&nbsp;</p>',70, 3);

--CASA DE LOS GOLFÍN Y SANTA MARTA
INSERT INTO objeto(oid, descripcion) VALUES (80,'Casa de los Golfín y Santa Marta');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (81, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/8-1.JPG', 80);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (82, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/8-2.JPG', 80);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (83, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/8-3.JPG', 80);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (80,'Casa de los Golfín y Santa Marta','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa de los Golfín y Santa Marta" width="190" height="143" src="upload/userfiles/image/8-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Este edificio fue reconstruido con elementos renacentistas del siglo XVI. En la fachada podemos apreciar su portada, en arco de medio punto con grandes dovelas, y por encima de ésta, una ventana flanqueada por dos escudos, uno de los Golfines y el otro de Portocarrero. En su interior puede verse un pequeño patio que, a pesar de tener un trazado irregular y contar sólo con dos lados porticados, resulta de gran armonía por el suave tratamiento de sus columnas y capiteles.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">En la actualidad se han instalado en esta casa algunos servicios técnicos de la Diputación Provincial de Cáceres.</p></span></td></tr></tbody></table><p>&nbsp;</p>',80, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (81,'House of Golfín and Santa Marta','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa of Golfín and Santa Marta" width="190" height="143" src="upload/userfiles/image/8-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">This building was rebuilt in the sixteenth century Renaissance elements. In the front we can see its cover, in a semicircular arch with large voussoirs, and above it, a window flanked by two shields, one of the Olive Ridley and the other Portocarrero. Inside you can see a small courtyard, despite having an irregular shape and having only two arcaded sides, is of great harmony for the smooth processing of your columns and capitals.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Some technical services of the  Diputación Provincial de Cáceres are currently installed in this house.</p></span></td></tr></tbody></table><p>&nbsp;</p>',80, 3);

--PALACIO DE LA DIPUTACIÓN PROVINCIAL DE CACERES
INSERT INTO objeto(oid, descripcion) VALUES (90,'Palacio de la Diputación Provincial de Cáceres');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (91, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/9-1.JPG', 90);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (92, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/9-2.JPG', 90);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (93, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/9-3.JPG', 90);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (90,'Palacio de la Diputación Provincial de Cáceres','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palacio de la Diputación Provincial de Cáceres" width="190" height="143" src="upload/userfiles/image/9-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Es un edificio de estilo renacentista, construido en el siglo XVI. Está asentado sobre el lugar que ocuparon el Palacio de Hernán Pérez de Ulloa y el Convento de Santa María de Jesús, fundado en el siglo XV por las monjas jerónimas. Su fachada procede del Colegio de San Pedro, Seminario del Obispo Galarza. La portada es adintelada, de frontón triangular, coronando las columnas laterales adosadas con escudos de Galarza. En el frontón hay una imagen de la Virgen irradiante, en el interior de un óvalo. En la esquina de la derecha hay otro escudo de Galarza.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Actualmente es la sede de la Diputación Provincial.</p></span></td></tr></tbody></table><p>&nbsp;</p>',90, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (91,'Palace of Diputación Provincial de Cáceres','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palace of Diputación Provincial de Cáceres" width="190" height="143" src="upload/userfiles/image/9-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">It is a Renaissance-style building, built in the sixteenth century. Sits on the place occupied the Palace of Hernan Perez de Ulloa and the Convent of Santa Maria de Jesus, founded in the fifteenth century by the nuns Hieronymite. Its facade is from the Colegio de San Pedro, Seminar Obispo Galarza. The cover is a lintel, a triangular pediment, columns crowned with attached side shields Galarza. On the pediment there is a radiant image of the Virgin, inside an oval. In the right corner there is another shield Galarza.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify"> It now houses the County Council.</p></span></td></tr></tbody></table><p>&nbsp;</p>',90, 3);

--CASA DE LOS GOLFINES DE ABAJO
INSERT INTO objeto(oid, descripcion) VALUES (100,'Casa de los Golfines de Abajo');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (101, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/10-1.JPG', 100);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (102, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/10-2.JPG', 100);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (103, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/10-3.JPG', 100);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (100,'Palacio de los Golfines de Abajo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa de los Golfines de Abajo" width="190" height="143" src="upload/userfiles/image/10-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">En este palacio se alojaron los Reyes Católicos, de ahí el escudo en la fachada plateresca y la alusión "Fer de Fer", Fernando (Golfín) de Fernando (el Católico)El tamaño de este palacio es considerable, ya que ocupó el espacio de casi una veintena de casas. Aún así, posee una de las fachadas más decorativas y vistosas del Conjunto Monumental. Alfíz, ventanas geminadas, escudos, cartelas, medallones al gusto clásico y un remate de grifos afrontados, similar al del Palacio de Monterrey de Salamanca, han hecho de este edificio uno de los más significativos y reproducido en múltiples soportes (pintura, fotografía, películas...)</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Situado en Plaza de los Golfines</p></span></td></tr></tbody></table><p>&nbsp;</p>',100, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (101,'Palace of Golfines de Abajo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palace Golfines de Abajo" width="190" height="143" src="upload/userfiles/image/10-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">The Catholic Kings stayed in this palace, hence the shield on the plateresque facade and the reference ‘Fer de Fer’, Fernando (Golfín) de Fernando (the Catholic).This palace is of a considerable size, occupying the space of nearly twenty houses. It has one of the most decorative, bright and colourful facades of the Monumental Ensemble. Alfiz, double windows, shields, cartouches and classical style medallions, all crowned by opposing griffins, similar to that of the Palace of Monterrey in Salamanca, have made this one of the most important buildings and most reproduced in multiple mediums (painting, photography, films, etc.).</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Situated in Plaza de los Golfines</p></span></td></tr></tbody></table><p>&nbsp;</p>',100, 3);

--CASA DE LOS BACERRA
INSERT INTO objeto(oid, descripcion) VALUES (110,'Casa de los Becerra');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (111, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/11-1.JPG', 110);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (112, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/11-2.JPG', 110);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (113, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/11-3.JPG', 110);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (110,'Casa de los Becerra','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa de los Becerra" width="190" height="143" src="upload/userfiles/image/11-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">El noble que la mandó construir, Luis de Becerra, la disfrutó poco, pues pasó casi toda su vida batallando por distintas causas. Curiosamente se dice que murió de una enfermedad en la cama. Imponente casa de finales del siglo XV y principios del XVI. Concentra los elementos propios de las fachadas de las mansiones cacereñas (puerta principal en arco de medio punto realizado con largas dovelas, alfíz, escudo) en muy poco espacio, no pareciendo lo amplia que realmente es.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">En ella está instalada la fundación Mercedes Calle y Carlos Ballesteros. Se puede visitar el interior.</p></span></td></tr></tbody></table><p>&nbsp;</p>',110, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (111,'House de los Becerra','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="House de los Becerra" width="190" height="143" src="upload/userfiles/image/11-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">The nobleman that ordered it to be built, Luis de Becerra, didn’t get to enjoy it much as he spent nearly his whole life fighting for various causes. Strangely, it is said that he died in bed from an illness.Imposing house dating from the end of the 15th and the beginning of the 16th century. The typical elements of the facades of mansions in Caceres (the main door in a semi-circular arch with large voussoirs, alfiz and shield) are concentrated in a very small space, so it doesn’t seem as big as it actually is.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">The Mercedes Calle and Carlos Ballesteros Foundation is installed inside, which can be visited.</p></span></td></tr></tbody></table><p>&nbsp;</p>',110, 3);

--CONVENTO DE LA COMPAÑÍA DE JESÚS
INSERT INTO objeto(oid, descripcion) VALUES (120,'Convento de la Compañía de Jesús');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (121, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/12-1.JPG', 120);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (122, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/12-2.JPG', 120);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (123, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/12-3.JPG', 120);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (120,'Colegio de la Compañía de Jesús','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Colegio de la Compañía de Jesús" width="190" height="143" src="upload/userfiles/image/12-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Antiguo Seminario Jesuita y Colegio Mayor "Luisa de Carvajal", en la actualidad acoge servicios territoriales de la Junta de Extremadura, la Filmoteca y el Centro de Exposiciones San Jorge y alberga anualmente la Feria de Arte Contemporáneo "Foro Sur"</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Plaza de San Jorge</p></span></td></tr></tbody></table><p>&nbsp;</p>',120, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (121,'College de la Compañía de Jesús','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="College de la Compañía de Jesús" width="190" height="143" src="upload/userfiles/image/12-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">The former Jesuit Seminary and Main College Luisa de Carvajal now houses local services of the Regional Government of Extremadura, the film library and the San Jorge Exhibition Centre and the annual Contemporary Art Fair, Foro, is held here.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Plaza de San Jorge</p></span></td></tr></tbody></table><p>&nbsp;</p>',120, 3);

--IGLESIA DE LA PRECIOSA SANGRE
INSERT INTO objeto(oid, descripcion) VALUES (130,'Iglesia de San Francisco Javier ');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (131, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/13-1.JPG', 130);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (132, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/13-2.JPG', 130);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (133, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/13-3.JPG', 130);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (130,'Iglesia de San Francisco Javier','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Iglesia de San Francisco Javier" width="190" height="143" src="upload/userfiles/image/13-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Este conjunto de Iglesia y Colegio construido por la Compañía de Jesús en el siglo XVIII, siguiendo el estilo barroco, preside un gran espacio en el centro de la Zona Monumental. La fachada de la iglesia tiene arco de medio punto y una hornacina cobijando la imagen de San Francisco Javier y está flanqueada por dos torres cuadradas rematadas piramidalmente. El interior es de una sola nave, con capillas laterales y cúpula sobre el crucero. El retablo mayor tiene columnas corintias enmarcando un lienzo que representa el "Milagro del Cangrejo".</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Está situada en la Plaza de San Jorge, entre las plazas más antiguas de Santa María y de San Mateo. La escultura de San Jorge, patrón de la ciudad, le da nombre y preside la plaza desde una hornacina.</p></span></td></tr></tbody></table><p>&nbsp;</p>',130, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (131,'Church of San Francisco Javier','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Church of San Francisco Javier" width="190" height="143" src="upload/userfiles/image/13-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">This joint church and college was built by the Company of Jesus in the 18th century. It is Baroque style and occupies a large area in the centre of the Monumental Area.The church’s facade has a semi-circular arch and a niche that shelters the image of San Francisco Javier and is flanked by two square towers that finish in pyramids.Inside is a single nave, with side chapels and a cupola over a stone cross. The main altarpiece has Corinthian columns framing a canvas that represents the ‘Miracle of the Crab’.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">This is in the Plaza de San Jorge, between the oldest squares of Santa María and San Mateo. The square takes its name from the sculpture of Saint George, the city’s Patron Saint, which presides over the square from a niche.</p></span></td></tr></tbody></table><p>&nbsp;</p>',130, 3);

--CASA DEL AGUILA
INSERT INTO objeto(oid, descripcion) VALUES (140,'Casa del Águila');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (141, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/14-1.JPG', 140);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (142, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/14-2.JPG', 140);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (143, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/14-3.JPG', 140);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (140,'Casa del Águila','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa del Águila" width="190" height="143" src="upload/userfiles/image/14-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Casa señorial que perteneció a la familia de los Sande, como así indica el escudo con el águila. En la fachada destaca una preciosa ventana gótica del siglo XV. Como muchos de estos palacetes, sus reformas de acondicionamiento se han sucedido en el tiempo.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Callejón de la Monja</p></span></td></tr></tbody></table><p>&nbsp;</p>',140, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (141,'House del Águila','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="House del Águila" width="190" height="143" src="upload/userfiles/image/14-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Stately home that belonged to the Sande family, as indicated by the shield with the eagle. In the facade there is a beautiful Gothic window from the 15th century.Like many of these small palaces it has undergone reformations over time.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Callejón de la Monja</p></span></td></tr></tbody></table><p>&nbsp;</p>',140, 3);

--CASA DE LOS SOLÍS
INSERT INTO objeto(oid, descripcion) VALUES (150,'Casa de los Solís');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (151, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/15-1.JPG', 150);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (152, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/15-2.JPG', 150);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (153, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/15-3.JPG', 150);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (150,'Casa de los Solís','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa de los Solís" width="190" height="143" src="upload/userfiles/image/15-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Acompaña a este edificio una leyenda sobre el origen del linaje; ya que al parecer consiguió el título nobiliario por un servicio a la Reina, al lograr llevar un mensaje desde Cáceres a Valladolid cabalgando durante una sola jornada.La concentración de elementos decorativos en una de las esquinas de la fachada no da una real idea de la gran extensión de este edificio del siglo XVI. Uno de ellos es el escudo de la familia Solís, compuesto por un Sol con los rayos mordidos por ocho cabezas de serpiente; otros son el yelmo, el matacán redondo, la puerta en arco de medio punto y el alfiz que va enmarcando todo.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">En la actualidad está habitado por una orden religiosa: los Padres de la Preciosa Sangre (cuya iglesia se encuentra cerca)</p></span></td></tr></tbody></table><p>&nbsp;</p>',150, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (151,'House de los Solís','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="House de los Solís" width="190" height="143" src="upload/userfiles/image/15-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">There is a legend connected to this building, about the origin of the lineage. It seems that they received the title of noble for a service to the Queen, that of managing to take a message from Caceres to Valladolid, on horseback, in only one day.The concentration of decorative elements in one of the corners of the facade gives us a real idea of the huge size of this building from the 16th century. One of these is the shield of the Solís family, composed of a sun with eight snake heads biting the rays; others are the helmet, the round machicolation, the door in a semi-circular arch and the alfiz that frames everything.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">This is now inhabited by a religious order: the Fathers de la Preciosa Sangre (whose church is nearby).</p></span></td></tr></tbody></table><p>&nbsp;</p>',150, 3);

--TORRE DE SANDE
INSERT INTO objeto(oid, descripcion) VALUES (160,'Torre de Sande');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (161, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/16-1.JPG', 160);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (162, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/16-2.JPG', 160);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (163, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/16-3.JPG', 160);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (160,'Torre de Sande','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Torre de Sande" width="190" height="143" src="upload/userfiles/image/16-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Impresionante torre construida en el siglo XIV, tratándose de una de las más antiguas de la ciudad. Presenta un soberbio matacán defensivo, además de una ventana geminada y otros elementos de estilo Gótico. Perteneció a una casa señorial hoy desaparecida. De hecho, lo único que queda en pie de la misma es esta torre.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Calle de Orellana</p></span></td></tr></tbody></table><p>&nbsp;</p>',160, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (161,'Tower of Sande','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Tower of Sande" width="190" height="143" src="upload/userfiles/image/16-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">This impressive tower, built in the 14th century, is one of the oldest in the city.It has a magnificent defensive machicolation, as well as a double window and other Gothic elements.It belonged to a stately home that has disappeared. In fact, this tower is the only thing that remains standing from it.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Calle de Orellana</p></span></td></tr></tbody></table><p>&nbsp;</p>',160, 3);

--IGLESIA DE SAN MATÉO
INSERT INTO objeto(oid, descripcion) VALUES (170,'Iglesia de San Matéo');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (171, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/17-1.JPG', 170);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (172, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/17-2.JPG', 170);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (173, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/17-3.JPG', 170);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (170,'Iglesia de San Matéo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Iglesia de San Matéo" width="190" height="143" src="upload/userfiles/image/17-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">La iglesia, construida en el siglo XVI, posiblemente sobre el solar ocupado por una antigua mezquita, tiene un proceso constructivo muy largo, de casi trescientos años. Destaca su portada con decoración plateresca. En el interior, el retablo mayor de pino en su color es obra de 1766, realizado por Vicente Barbadillo. La capilla de los Sande, actual sacristía, tiene el interior gótico con una hermosa bóveda de crucería estrellada. En los muros se encuentran los enterramientos de las familias nobles de la ciudad: Ovando, Golfines, Paredes, Saavedra, etc.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Está ubicada en la plaza del mimo nombre. Parece que fue la plaza de armas de la ciudad musulmana. En la Edad Media y principios de la Edad Moderna, fue una de las dos colaciones intramuros en torno a las cuales se disponían los palacios y casas fuertes de las más importantes familias nobiliarias.</p></span></td></tr></tbody></table><p>&nbsp;</p>',170, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (171,'Church of San Mateo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Church of San Mateo" width="190" height="143" src="upload/userfiles/image/17-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">The church, built in the 16th century, possibly over the site of an old mosque, took a long time, almost three hundred years, to build. It has an outstanding facade, with plateresque decoration.Inside, the main altarpiece is pine-coloured and was made by Vicente Barbadillo in 1766. The Chapel de los Sande, now the sacristy, is Gothic inside, with a beautiful ribbed star vault. There are the tombs of the city’s noble families in the walls: Ovando, Golfines, Paredes, Saavedra, etc.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">It is in the square of the same name. It appears to have been the weapons square in the Muslim city. In the Middle Ages and the beginning of the Modern Age it was one of the locations within the walls around which the palaces and fortified houses of the most important noble families were built.</p></span></td></tr></tbody></table><p>&nbsp;</p>',170, 3);

--TORRE DE LAS CIGÜEÑAS
INSERT INTO objeto(oid, descripcion) VALUES (180,'Palacio de las Cigüeñas');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (181, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/18-1.JPG', 180);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (182, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/18-2.JPG', 180);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (183, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/18-3.JPG', 180);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (180,'Palacio de las Cigüeñas','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palacio de las Cigüeñas" width="190" height="143" src="upload/userfiles/image/18-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Es un edificio equilibrado, del que destaca su torre, mucho más elevada que las del resto de los palacios del conjunto monumental, debido a que cuando la Reina Isabel la Católica mandó desmochar las torres cacereñas, hizo una excepción con este que entonces se estaba construyendo por orden del capitán Diego de Ovando, vasallo y miembro de su Real Consejo.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">Actual sede de la Comandancia Militar de Cáceres, en su interior se encuentra una colección de armas, conocida como el Museo de Armas. Se suelen organizar exposiciones con cierta asiduidad.</p></span></td></tr></tbody></table><p>&nbsp;</p>',180, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (181,'Palace de las Cigüeñas','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Palace de las Cigüeñas" width="190" height="143" src="upload/userfiles/image/18-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">This is a well-balanced building, in which the tower stands out, being much higher than those of the rest of the palaces in the Monumental Ensemble, as when the Queen Isabel the Catholic ordered all the towers of Caceres to be lopped off she made an exception of this one, which was at that time being built on the orders of Captain Diego de Ovando, vassal and member of her Royal Council.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">This is now the Military Command Headquarters of Caceres, with a collection of weapons, known as the Weapons Museum, inside. They usually organize exhibitions fairly regularly.</p></span></td></tr></tbody></table><p>&nbsp;</p>',180, 3);

--CASA DE LAS VELETAS
INSERT INTO objeto(oid, descripcion) VALUES (190,'Casa de las Veletas');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (191, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/19-1.JPG', 190);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (192, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/19-2.JPG', 190);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (193, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/19-3.JPG', 190);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (190,'Casa de las Veletas','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Casa de las Veletas" width="190" height="143" src="upload/userfiles/image/19-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Este solar que ocupan ahora el Palacio de las Veletas y la Casa de los Caballos estaba destinado anteriormente a Alcazaba árabe. Prueba de ello es su aljibe de los siglos XI-XII. El resto de lo que actualmente puede verse del edificio es obra de los siglos XV, XVII y XVIII.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">El Museo de Cáceres contiene una colección que abarca desde la Prehistoria hasta la época Visigoda, otra de Etnografía, además del aljibe hispano-árabe y la colección de Bellas Artes con obras del Museo del Prado (Lucas Jordán, Vicente Carducho, Antonio Mª Esquivel...), del Obispado de Coria-Cáceres (tallas, pinturas y obras de orfebrería religiosa) y de la Diputación Provincial (obras de artistas contemporáneos como Alberto Sánchez, Canogar, Chirino, Genovés, Gordillo, Millares, Oteiza, Palazuelo, Saura, Vostell, Zóbel... ). Además cuenta con una sala de exposiciones temporales.</p></span></td></tr></tbody></table><p>&nbsp;</p>',190, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (191,'House de las Veletas','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="House de las Veletas" width="190" height="143" src="upload/userfiles/image/19-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">This spot, which is now occupied by the Palace de las Veletas and the House de los Caballos, was previously the site of an Arabic Alcazaba (citadel). The cistern from the 11th to 12th centuries is proof of this. The rest of what you can now see of the building dates from the 15th, 17th and 18th centuries.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">The Museum of Caceres has one collection that spans from prehistory to the Visigoth era and another of ethnography, as well as the Hispanic-Arabic cistern and the collection of Fine Arts with works from the Prado Museum (Lucas Jordán, Vicente Carducho, Antonio Mª Esquivel, etc.), the Bishopric of Coria-Caceres (sculptures, paintings and religious articles of gold and silver) and the Provincial Council (works by contemporary artists such as Alberto Sánchez, Canogar, Chirino, Genovés, Gordillo, Millares, Oteiza, Palazuelo, Saura, Vostell, Zóbel, etc.). It also has a temporary exhibition room.</p></span></td></tr></tbody></table><p>&nbsp;</p>',190, 3);

--CONVENTO DE SAN PABLO
INSERT INTO objeto(oid, descripcion) VALUES (200,'Convento de San Pablo');
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (201, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/20-1.JPG', 200);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (202, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/20-2.JPG', 200);
INSERT INTO plantilla(oid, ruta, imagen, objeto_oid) VALUES (203, '/PFC/WebRatio/WebRatio Enterprise 6.0.0Beta/Tomcat/webapps/Real-A/', 'upload/caceres/20-3.JPG', 200);

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (200,'Convento de San Pablo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Convento de San Pablo" width="190" height="143" src="upload/userfiles/image/20-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Beaterio fundado en el siglo XV, más tarde fue erigido convento. Sigue modelos góticos en la portada de la iglesia. En el convento residen aún monjas clarisas. Otros conventos habitados son el Convento de Santa Clara, en la plaza del mismo nombre, y el Convento de las Jerónimas, en la antigua Enfermería de San Antonio, en la calle Olmo.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">En este convento de monjas de clausura se pueden comprar dulces artesanales de gran fama.</p></span></td></tr></tbody></table><p>&nbsp;</p>',200, 2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (201,'Convent of San Pablo','<table border="0" cellspacing="0" cellpadding="0" width="300" align="center" style="clear: both"><tbody><tr><td><div style="text-align: center"><img alt="Convent of San Pablo" width="190" height="143" src="upload/userfiles/image/20-0.jpg" /></div></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><strong>Descripci&oacute;n:</strong></td></tr><tr><td bgcolor="#ffffff"><p style="text-align: justify">Beaterio (convent for lay sisters) founded in the 15th century, with the actual convent being built later. The church’s facade is in the Gothic style. Nuns of the Order of Saint Clare live in the convent. Other inhabited convents are that of Santa Clara, in the square of the same name, and the Convent de las Jerónimas, in the old Infirmary of San Antonio, in Olmo Street.</p></td></tr></tbody></table><table border="1" cellspacing="0" cellpadding="0" width="300" align="center"><tbody><tr><td bgcolor="#6699ff" valign="top" colspan="2"><span class="texto_fichas"><strong>Observaciones:</strong></span></td></tr><tr><td bgcolor="#ffffff" valign="top"><span class="texto"><p style="text-align: justify">In this convent of cloistered nuns you can buy hand-made sweets of huge renown.</p></span></td></tr></tbody></table><p>&nbsp;</p>',200, 3);

--SIN CORRESPONDENCIA
INSERT INTO objeto(oid, descripcion) VALUES (999,'Sin Correspondencia');

INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (9991,'No se encontró correspondencia','<p><strong>No se encontr&oacute; Correspondencia</strong></p>',999,2);
INSERT INTO descripciones(oid, descripcion, informacion, objeto_oid, idioma_oid) VALUES (9992,'No Result','<p><strong>No Result</strong></p>',999,3);
